### ISSUE TITLE
Amend CI deployment scripts

### ISSUE THREAD

**Issue by spences10** [spences10/blog.scottspence.me#81]
https://docs.travis-ci.com/user/deployment/script/

Example
```yaml
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: npm run alias:dev
    on:
      branch: develop
  # deploy master to production
  - provider: script
    script: npm run alias:prod
    on:
      branch: master
```
